### ISSUE TITLE
man page start examples incorrect

### ISSUE THREAD

**Issue by sodface** [tio/input-emulator#1]
https://github.com/tio/input-emulator/blob/deb635b5f64d1d15ad2918be824d29c2ee8d0096/man/input-emulator.1.in#L197
https://github.com/tio/input-emulator/blob/deb635b5f64d1d15ad2918be824d29c2ee8d0096/man/input-emulator.1.in#L203
https://github.com/tio/input-emulator/blob/deb635b5f64d1d15ad2918be824d29c2ee8d0096/man/input-emulator.1.in#L214

Should be:

```
input-emulator start kbd|mouse|touch
```

**Comment by lundmar** [comment]
Fixed in 6c35040e6fc4f65ce0519ee76d00d60490bcb987

Thanks for reporting the issue.
