### ISSUE TITLE
does not start device

### ISSUE THREAD

**Issue by mashrit** [tio/input-emulator#3]
so i just installed this and followed all the described steps, 
now i first start the mouse, it shows
```
$ input-emulator start mouse --x-max 1366 --y-max 768
Starting input-emulator service...
```
then i try to move the mouse
```
$ input-emulator mouse move 200 -300
Please start service using the 'input-emulator start <device>' command
```
even the status shows this 
```
$input-emulator status
Please start service using the 'input-emulator start <device>' command
```

**Comment by lundmar** [comment]
Please check that you have the /dev/uinput device.

If it exists you may not have the permissions to access it.

**Comment by mashrit** [comment]
yes, the file exists 
but i do not seem to have permission to it
how do i obtain those?

**Comment by lundmar** [comment]
Try https://github.com/tio/input-emulator#42-set-up-permissions-for-devuinput

**Comment by mashrit** [comment]
ok, figured out the issue, it took me too long
[here](https://github.com/tio/input-emulator#42-set-up-permissions-for-devuinput), it says make udev rule
`KERNEL==”uinput”, GROUP=”uinput”, MODE:=”0660″`

but those double ticks are wrong, it should be`
KERNEL=="uinput", GROUP="uinput", MODE:="0660"`
